#!/usr/bin/env ruby

require 'yaml'

POSTS_DIR = '_posts/'
TAGS_DIR = 'tags/'
tags = {}
Dir.foreach(POSTS_DIR) do |post|

  next if post == '.' or post == '..' or post == '.DS_Store'
  postYaml = YAML.load_file(POSTS_DIR + post)
  unless (postYaml['tags'] == nil)
    postYaml['tags'].each{|tag|

      if( tags[tag] )
        tags[tag] = tags[tag] + 1
      else
        tags[tag] = 1
      end
      tag.downcase!
      unless File.exist?(TAGS_DIR + tag + '.html')

        puts('[+] Generating #' + tag + ' page')

        File.open(TAGS_DIR + tag + '.html', 'w') {|f| f.write(
        "---\nlayout: tag\nsection-type: tag\ntitle: " + tag + "\n---\n## Tag")}

      end
    }
  end

end
File.open('_data/tags.yml', 'w'){|f| YAML.dump(tags, f)}